### ISSUE TITLE
Satış Verilerinin Analizi

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#10]
### Görevin Tanımı
Toplanan ve temizlenen satış verilerinin detaylı analizinin yapılması.

### Görevler
- [ ] Verilerin incelenmesi
- [ ] Analiz yöntemlerinin belirlenmesi
- [ ] Satış trendlerinin analizi
- [ ] Anlamlı ilişkilerin ve korelasyonların bulunması

### Etiketler
- Veri Analizi

### Milestone
- Aşama 2: Veri Analizi ve Görselleştirme
