### ISSUE TITLE
BI Tool Kurulumu ve Yapılandırılması

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#12]
### Görevin Tanımı
BI tool'un kurulumu ve gerekli yapılandırmaların yapılması.

### Görevler
- [ ] Uygun BI tool'un seçimi (örneğin, Tableau, Power BI, Qlik Sense)
- [ ] BI tool'un kurulumu
- [ ] Kullanıcı hesaplarının oluşturulması
- [ ] Veri bağlantılarının yapılandırılması

### Etiketler
- BI Tool Entegrasyonu

### Milestone
- Aşama 3: BI Tool Entegrasyonu
