### ISSUE TITLE
Veri Kaynaklarının Entegrasyonu

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#13]
### Görevin Tanımı
BI tool'a veri kaynaklarının eklenmesi ve veri entegrasyonunun sağlanması.

### Görevler
- [ ] Veri tabanına bağlantının kurulması
- [ ] Veri kaynaklarının eklenmesi
- [ ] Veri akışlarının doğrulanması

### Etiketler
- BI Tool Entegrasyonu

### Milestone
- Aşama 3: BI Tool Entegrasyonu
