### ISSUE TITLE
Dashboard'un Canlıya Alınması

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#15]
### Görevin Tanımı
Dashbord'un son kullanıcılar için canlıya alınması ve erişimin sağlanması.

### Görevler
- [ ] Kullanıcı erişim izinlerinin ayarlanması
- [ ] Canlıya geçiş için gerekli testlerin yapılması
- [ ] Son kullanıcı eğitimlerinin verilmesi
- [ ] Canlıya geçiş

### Etiketler
- BI Tool Entegrasyonu

### Milestone
- Aşama 3: BI Tool Entegrasyonu
