### ISSUE TITLE
Veri Seti Hazırlığı ve Model Eğitimi

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#16]
### Görevin Tanımı
Veri setinin hazırlanması ve makine öğrenmesi modelinin eğitilmesi.

### Görevler
- [x] Veri setinin hazırlanması ve temizlenmesi
- [ ] Özellik mühendisliği ve özellik seçimi
- [ ] Modelin seçimi ve kurulması
- [ ] Modelin eğitilmesi

### Etiketler
- Makine Öğrenmesi

### Milestone
- Aşama 4: Makine Öğrenmesi
