### ISSUE TITLE
Model Değerlendirme ve İyileştirme

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#17]
### Görevin Tanımı
Eğitilen makine öğrenmesi modelinin değerlendirilmesi ve iyileştirilmesi.

### Görevler
- [x] Modelin performansının değerlendirilmesi
- [x] Modelin doğruluk ve hatanın belirlenmesi
- [x] Modelin hiperparametrelerinin ayarlanması
- [x] Modelin iyileştirilmesi ve tekrar değerlendirilmesi

### Etiketler
- Makine Öğrenmesi

### Milestone
- Aşama 4: Makine Öğrenmesi

**Comment by AshNumpy** [comment]
**Sonuçlar:**

Öncelikle yorumum şudur ki verilerin kalitesinin ve gözlem sayısının düşük olmasından ötürü sonuçlar tatmin edici olarak çıkmadı. Veri ön işleme ve feature extraction ile başarıları arttırmalara yönelik çalışmalar yapıldı ve testlerin sonuçları aşağıdaki gibi elde edildi.

| Model                     | RMSE         | MAE          | MAPE        | R2       | İşlem                         |
|:--------------------------|:------------:|:------------:|:-----------:|:--------:|:-----------------------------:|
| GradientBoostingRegressor | 1075.787854  | 847.604850   | 39.047753   | 0.188607 🟠 | Default Model Değerlendirmesi |
| XGBRegressor              | 1079.576688  | 856.652389   | 39.410341   | 0.182882 🟠 | Default Model Değerlendirmesi |
| DecisionTreeRegressor     | 1130.127102  | 912.703563   | 42.143135   | 0.104568 | Default Model Değerlendirmesi |
| RandomForestRegressor     | 1135.109433  | 919.734190   | 42.219454   | 0.096655 | Default Model Değerlendirmesi |
| LinearRegression          | 1167.415239  | 954.289812   | 43.627632   | 0.044504 | Default Model Değerlendirmesi |
| GradientBoostingRegressor | 0.419886  | 0.329024  | 4.255063 | 0.142835 | Log Dönüşümlü Değerlendirme  |
| XGBRegressor              | 0.419088  | 0.329057  | 4.256116 | 0.146089 | Log Dönüşümlü Değerlendirme  |
| RandomForestRegressor     | 0.434384  | 0.351478  | 4.543721 | 0.082621 | Log Dönüşümlü Değerlendirme  |
| DecisionTreeRegressor     | 0.445797  | 0.358989  | 4.641508 | 0.033780 | Log Dönüşümlü Değerlendirme  |
| LinearRegression          | 0.444062  | 0.361695  | 4.674005 | 0.041283 | Log Dönüşümlü Değerlendirme  |
| XGBRegressor              | 1066.6029 | 840.0428  | 38.7713  | 0.2024 🟢 | Hiperparametre Ayarı          |
| GradientBoostingRegressor | 1069.5826 | 853.2354  | 39.4834  | 0.1979   | Hiperparametre Ayarı          |
| XGBRegressor              | 1009.3078 | 802.4083  | 37.4648  | 0.1575   | Hiperparametre Ayarı + Aykırı Değerlerin Düşürülmesi |
| GradientBoostingRegressor | 1015.3781 | 817.1371  | 38.2017  | 0.1474   | Hiperparametre Ayarı + Aykırı Değerlerin Düşürülmesi |
| Ensemble                   | 1064.8658 | 842.7579  | 38.9603  | 0.2050 🟢 | XGBoost + GBRegressor |
| Meta Model: Linear Regression             | 1066.5585  | 847.1679   | 0.392173  | 0.202469 🟢 | Stacking Yöntemi |
| Meta Model: GB Regressor   | 1075.4891  | 861.8766   | 0.398928  | 0.189058 🟠 | Stacking Yöntemi |
| Meta Model: Random Forest Regressor       | 1075.8063  | 857.0143   | 0.396717  | 0.188579 🟠 | Stacking Yöntemi |
| Meta Model: Support Vector Regressor      | 1171.2793  | 941.4644   | 0.407620  | 0.038169  | Stacking Yöntemi |
| Meta Model: XGBoost Regressor             | 1098.0239  | 869.6954   | 0.399957  | 0.154718  | Stacking Yöntemi |

Bu sonuçlar ışığında base model olarak `GradientBoostingRegressor` ve `XGBoost` ile stack edilmiş `LinearRegression` modeli seçilebilir.
