### ISSUE TITLE
Web Uygulaması Geliştirme ve Entegrasyonu

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#19]
### Görevin Tanımı
Web uygulamasının geliştirilmesi ve makine öğrenmesi modelinin entegrasyonunun yapılması.

### Görevler
- [ ] Front-end geliştirme
- [ ] Back-end geliştirme
- [ ] Veri tabanı entegrasyonu
- [ ] Makine öğrenmesi modelinin entegrasyonu

### Etiketler
- Web Uygulaması Geliştirme

### Milestone
- Aşama 5: Web Uygulaması Geliştirme
