### ISSUE TITLE
Veri Tabanı Yapısının Tasarımı

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#4]
### Görevin Tanımı
Veri tabanının yapısının tasarlanması ve verilerin uygun şekilde depolanmasının sağlanması.

### Görevler
- [ ] Veri tabanı gereksinimlerinin belirlenmesi
- [ ] Veri tabanı yapısının tasarımı
- [ ] Veri tabanının oluşturulması

### Etiketler
- Veri Hazırlığı

### Milestone
- Aşama 1: Veri Hazırlığı
