### ISSUE TITLE
Anormal ve Hatalı Verilerin Tespiti ve Düzeltilmesi

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#7]
### Görevin Tanımı
Anormal ve hatalı verilerin tespit edilmesi ve düzeltilmesi işlemi.

### Görevler
- [ ] Anormal verilerin tespit edilmesi
- [ ] Hatalı verilerin tespiti
- [ ] Anormal ve hatalı verilerin düzeltilmesi

### Etiketler
- Veri Hazırlığı

### Milestone
- Aşama 1: Veri Hazırlığı
