### ISSUE TITLE
Veri Formatlarının Düzeltilmesi

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Sales-End-to-End-ML-Project#8]
### Görevin Tanımı
Veri formatlarının standart hale getirilmesi ve düzenlenmesi işlemi.

### Görevler
- [ ] Tarih formatlarının düzenlenmesi
- [ ] Sayısal formatların düzenlenmesi
- [ ] Diğer formatların düzenlenmesi

### Etiketler
- Veri Hazırlığı

### Milestone
- Aşama 1: Veri Hazırlığı
